export type UserManagementTab = 'active' | 'pending' | 'blocked';

export type UserManagementRow = {
  id: string;
  name: string;
  email: string;
  userType: string;
  accessType: string;
  appAccessTags: string[];
  appAccessOverflowCount?: number;
  lastLogin: string;
  lastLoginAt: number;
  tab: UserManagementTab;
};

const APP_ACCESS_TAGS = [
  'Customer Perception',
  'Shopper behavior',
  'Insights Activation',
  'Digital Landscape',
  'Report builder',
];

const LAST_LOGIN = '01-03-2021, 7:15am';
const LAST_LOGIN_AT = new Date('2021-01-03T07:15:00').getTime();

export const USER_MANAGEMENT_ROWS: UserManagementRow[] = [
  {
    id: 'user-1',
    name: 'Ava Thompson',
    email: 'ava.thompson@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-2',
    name: 'Liam Patel',
    email: 'liam.patel@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-3',
    name: 'Noah Kim',
    email: 'noah.kim@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-4',
    name: 'Mia Rodriguez',
    email: 'mia.rodriguez@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-5',
    name: 'Ethan Walker',
    email: 'ethan.walker@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-6',
    name: 'Sophia Chen',
    email: 'sophia.chen@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-7',
    name: 'Mason Brooks',
    email: 'mason.brooks@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-8',
    name: 'Olivia Davis',
    email: 'olivia.davis@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-9',
    name: 'Lucas Green',
    email: 'lucas.green@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-10',
    name: 'Isabella Nguyen',
    email: 'isabella.nguyen@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-11',
    name: 'Benjamin Scott',
    email: 'benjamin.scott@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-12',
    name: 'Charlotte Perez',
    email: 'charlotte.perez@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'active',
  },
  {
    id: 'user-13',
    name: 'Amelia Johnson',
    email: 'amelia.johnson@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'pending',
  },
  {
    id: 'user-14',
    name: 'James Wilson',
    email: 'james.wilson@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Single supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'pending',
  },
  {
    id: 'user-15',
    name: 'Harper Moore',
    email: 'harper.moore@acme.com',
    userType: 'Basic 3P agency',
    accessType: 'Multiple supplier',
    appAccessTags: APP_ACCESS_TAGS,
    appAccessOverflowCount: 2,
    lastLogin: LAST_LOGIN,
    lastLoginAt: LAST_LOGIN_AT,
    tab: 'blocked',
  },
];
